package com.codex.flashsale.admin;

public enum AdminActivityAction {
    AUTH_LOGIN_SUCCESS,
    AUTH_LOGIN_FAILURE,
    AUTH_TOKEN_REFRESH,
    AUTH_LOGOUT,
    CAMPAIGN_CREATED,
    CAMPAIGN_UPDATED,
    CAMPAIGN_ACTIVATED,
    CAMPAIGN_ENDED,
    OUTBOX_RETRY_TRIGGERED,
    RECONCILIATION_RUN_TRIGGERED,
    RECONCILIATION_DRIFT_RESOLVED,
    TIKTOK_INGRESS_REPLAY_TRIGGERED,
    OPS_COPILOT_ANALYSIS_REQUESTED
}
